/* Generated By:JavaCC: Do not edit this line. WQLParserConstants.java */
package javax.wbem.query;

public interface WQLParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 5;
  int FORMAL_COMMENT = 6;
  int MULTI_LINE_COMMENT = 7;
  int notEqualsOperator = 8;
  int lessThanOrEqualsOperator = 9;
  int lessThanOperator = 10;
  int equalsOperator = 11;
  int greaterThanOrEqualsOperator = 12;
  int greaterThanOperator = 13;
  int plusSign = 14;
  int minusSign = 15;
  int asterisk = 16;
  int solidus = 17;
  int leftParen = 18;
  int rightParen = 19;
  int period = 20;
  int comma = 21;
  int or = 22;
  int and = 23;
  int not = 24;
  int select = 25;
  int from = 26;
  int where = 27;
  int like = 28;
  int escape = 29;
  int isa = 30;
  int approximateNumericLiteral = 31;
  int EXPONENT = 32;
  int unsignedInteger = 33;
  int characterStringLiteral = 34;
  int identifier = 35;
  int columnidentifier = 36;
  int letter = 37;
  int digit = 38;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<SINGLE_LINE_COMMENT>",
    "<FORMAL_COMMENT>",
    "<MULTI_LINE_COMMENT>",
    "\"<>\"",
    "\"<=\"",
    "\"<\"",
    "\"=\"",
    "\">=\"",
    "\">\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\".\"",
    "\",\"",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"select\"",
    "\"from\"",
    "\"where\"",
    "\"like\"",
    "\"escape\"",
    "\"isa\"",
    "<approximateNumericLiteral>",
    "<EXPONENT>",
    "<unsignedInteger>",
    "<characterStringLiteral>",
    "<identifier>",
    "<columnidentifier>",
    "<letter>",
    "<digit>",
  };

}
